config/routes.rb
Rails.application.routes.draw do


	#cut off www
	constraints(:host => /^www\./) do
		get "(*x)" => redirect { |params, request|
			ap URI.parse(request.url).tap {|url| url.host.sub!('www.', '') }.to_s
			URI.parse(request.url).tap {|url| url.host.sub!('www.', '') }.to_s
		}
	end
	namespace :admin do
		resources :users
		resources :teams 
    resources :mutants
    resources :tasks
		root to: 'teams#index'
	end

	devise_for :users,
		path_names: { sign_in: 'login', sign_out: 'logout', sign_up: 'signup' },
		sign_out_via: [:post, :delete, :get],
		controllers: { registrations: "users/registrations" }

	root to: 'front/landing#index'
end

app/models/task.rb
class Task < ActiveRecord::Base
  validates_presence_of :name
  validates_uniqueness_of :name
  belongs_to :team
  def destroyable?
    team.blank?
  end
end

app/controllers/admin/tasks_controller.rb
class Admin::TasksController < Admin::SpaceController
  before_action :set_task, only: [:show, :edit, :update, :destroy]

  # GET /tasks
  # GET /tasks.json
  def index
    @tasks = Task.all
  end

  # GET /tasks/1
  # GET /tasks/1.json
  def show
  end

  # GET /tasks/new
  def new
    @task = Task.new
  end

  # GET /tasks/1/edit
  def edit
  end

  # POST /tasks
  # POST /tasks.json
  def create
    @task = Task.new(task_params)

    respond_to do |format|
      if @task.save
        format.html { redirect_to admin_tasks_path, notice: 'Task was successfully created.' }
        format.json { render :show, status: :created, location: @task }
      else
        format.html { render :new }
        format.json { render json: @task.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tasks/1
  # PATCH/PUT /tasks/1.json
  def update
    respond_to do |format|
      if @task.update(task_params)
        format.html { redirect_to admin_tasks_path, notice: 'Task was successfully updated.' }
        format.json { render :show, status: :ok, location: @task }
      else
        format.html { render :edit }
        format.json { render json: @task.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tasks/1
  # DELETE /tasks/1.json
  def destroy
    @task.destroy
    respond_to do |format|
      format.html { redirect_to admin_tasks_path, notice: 'Task was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_task
      @task = Task.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def task_params
      params.require(:task).permit(:name, :is_completed, :team_id)
    end
end

app/views/admin/tasks/_form.html.haml
= simple_form_for([:admin,@task]) do |f|
  - if @task.errors.any?
    #error_explanation
      %h2
        = pluralize(@task.errors.count, "error")
        prohibited this task from being saved:
      %ul
        - @task.errors.full_messages.each do |message|
          %li= message
  = f.input :name, input_html: {maxlength: 30}
  = f.input :is_completed
  = f.input :team_id, collection: Team.unlinked_or_for_task(@task).map{|t| [t.name,t.id]}, include_blank: true, label: "Team"
  .actions
    = f.submit( class: "ui submit button")

app/views/admin/tasks/edit.html.haml
%h1.ui.header Editing task

= render 'form'

= link_to 'Back', admin_tasks_path, class: "ui small button blue"

app/views/admin/tasks/index.html.haml
%h1 Listing tasks

%table.ui.table
  %thead
    %tr
      %th Name
      %th is completed
      %th Team
      %th
      %th

  %tbody
  - @tasks.each do |task|
    %tr
      %td= task.name
      %td= task.is_completed
      %td
        = link_to task.team.name, edit_admin_team_path(task.team) unless task.team.blank?
      %td= link_to 'Edit', edit_admin_task_path(task), {class: "ui small button"}

      %td= link_to 'Destroy', admin_task_path(task), :method => :delete, :data => { :confirm => 'Are you sure?' }, class: "ui small button red" if task.destroyable?

%br

= link_to 'New Task', new_admin_task_path, class: "ui large button blue"

app/views/admin/tasks/new.html.haml
%h1 New task

= render 'form'

= link_to 'Back', admin_tasks_path, class: "ui small button blue"

app/views/admin/tasks/show.html.haml
%p#notice= notice

%p
  %b Name:
  = @task.name
%p
  %b Is completed:
  = @task.is_completed

= link_to 'Edit', edit_task_path(@task)
\|
= link_to 'Back', tasks_path