config/routes.rb
Rails.application.routes.draw do


	#cut off www
	constraints(:host => /^www\./) do
		get "(*x)" => redirect { |params, request|
			ap URI.parse(request.url).tap {|url| url.host.sub!('www.', '') }.to_s
			URI.parse(request.url).tap {|url| url.host.sub!('www.', '') }.to_s
		}
	end
	namespace :admin do
		resources :users
		resources :teams 
    resources :mutants
    resources :tasks
		root to: 'teams#index'
	end

	devise_for :users,
		path_names: { sign_in: 'login', sign_out: 'logout', sign_up: 'signup' },
		sign_out_via: [:post, :delete, :get],
		controllers: { registrations: "users/registrations" }

	root to: 'front/landing#index'
end

app/models/mutant.rb
class Mutant < ActiveRecord::Base
  validates_presence_of :name
  validates_uniqueness_of :name
  has_many :mutant_team_assignments, dependent: :destroy
  has_many :teams, through: :mutant_team_assignments
  def destroyable?
    teams.count==0
  end
end

app/controllers/admin/mutants_controller.rb
class Admin::MutantsController < Admin::SpaceController
  before_action :set_mutant, only: [:show, :edit, :update, :destroy]

  # GET /mutants
  # GET /mutants.json
  def index
    @mutants = Mutant.all
  end

  # GET /mutants/1
  # GET /mutants/1.json
  def show
  end

  # GET /mutants/new
  def new
    @mutant = Mutant.new
  end

  # GET /mutants/1/edit
  def edit
  end

  # POST /mutants
  # POST /mutants.json
  def create
    @mutant = Mutant.new(mutant_params)

    respond_to do |format|
      if @mutant.save
        format.html { redirect_to admin_mutants_path, notice: 'Mutant was successfully created.' }
        format.json { render :show, status: :created, location: @mutant }
      else
        format.html { render :new }
        format.json { render json: @mutant.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /mutants/1
  # PATCH/PUT /mutants/1.json
  def update
    respond_to do |format|
      if @mutant.update(mutant_params)
        format.html { redirect_to admin_mutants_path, notice: 'Mutant was successfully updated.' }
        format.json { render :show, status: :ok, location: @mutant }
      else
        format.html { render :edit }
        format.json { render json: @mutant.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /mutants/1
  # DELETE /mutants/1.json
  def destroy
    @mutant.destroy
    respond_to do |format|
      format.html { redirect_to admin_mutants_path, notice: 'Mutant was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_mutant
      @mutant = Mutant.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def mutant_params
      params.require(:mutant).permit(:name, team_ids: [])
    end
end

app/views/admin/mutants/_form.html.haml
= simple_form_for([:admin,@mutant]) do |f|
  - if @mutant.errors.any?
    #error_explanation
      %h2
        = pluralize(@mutant.errors.count, "error")
        prohibited this mutant from being saved:
      %ul
        - @mutant.errors.full_messages.each do |message|
          %li= message
  = f.input :name, input_html: {maxlength: 30}
  = f.association :teams, input_html: {maxlength: 30}
  .actions
    = f.submit( class: "ui submit button")

app/views/admin/mutants/edit.html.haml
%h1 Editing mutant

= render 'form'

= link_to 'Back', admin_mutants_path, class: "ui small button blue"

app/views/admin/mutants/index.html.haml
%h1 Listing mutants

%table.ui.table
  %tr
    %th Name
    %th Teams
    %th
    %th
    %th

  - @mutants.each do |mutant|
    %tr
      %td= mutant.name
      %td
        - mutant.teams.each do |team|
          = link_to team.name, edit_admin_team_path(team)
          %br/
      %td= link_to 'Edit', edit_admin_mutant_path(mutant), {class: "ui small button"}
      %td= link_to 'Destroy', admin_mutant_path(mutant), :method => :delete, :data => { :confirm => 'Are you sure?' }, class: "ui small button red" if mutant.destroyable?

%br

= link_to 'New Mutant', new_admin_mutant_path, class: "ui small button blue"

app/views/admin/mutants/new.html.haml
%h1 New mutant

= render 'form'

= link_to 'Back', admin_mutants_path, class: "ui small button blue"

app/views/admin/mutants/show.html.haml
%p#notice= notice

%p
  %b Name:
  = @mutant.name

= link_to 'Edit', edit_mutant_path(@mutant)
\|
= link_to 'Back', mutants_path