config/routes.rb
Rails.application.routes.draw do


	#cut off www
	constraints(:host => /^www\./) do
		get "(*x)" => redirect { |params, request|
			ap URI.parse(request.url).tap {|url| url.host.sub!('www.', '') }.to_s
			URI.parse(request.url).tap {|url| url.host.sub!('www.', '') }.to_s
		}
	end
	namespace :admin do
		resources :users
		resources :teams 
    resources :mutants
    resources :tasks
		root to: 'teams#index'
	end

	devise_for :users,
		path_names: { sign_in: 'login', sign_out: 'logout', sign_up: 'signup' },
		sign_out_via: [:post, :delete, :get],
		controllers: { registrations: "users/registrations" }

	root to: 'front/landing#index'
end

app/models/team.rb
class Team < ActiveRecord::Base
  validates_presence_of :name
  validates_uniqueness_of :name
  has_many :mutant_team_assignments, dependent: :destroy
  has_many :mutants, through: :mutant_team_assignments
  has_many :tasks
  def destroyable?
    true #mutants.count==0 and tasks.count==0
  end
  scope :unlinked_or_for_task, ->(r) do 
    joins('LEFT OUTER JOIN tasks ON tasks.team_id = teams.id').
      select('teams.*').
      group('teams.id').
      having('count(tasks.id) = 0 or tasks.id = ?', r.id)
  end
end

app/controllers/admin/teams_controller.rb
class Admin::TeamsController < Admin::SpaceController
  before_action :set_team, only: [:show, :edit, :update, :destroy]

  # GET /admin/teams
  # GET /admin/teams.json
  def index
    @teams = Team.all
  end

  # GET /admin/teams/1
  # GET /admin/teams/1.json
  def show
  end

  # GET /admin/teams/new
  def new
    @team = Team.new
  end

  # GET /admin/teams/1/edit
  def edit
  end

  # POST /admin/teams
  # POST /admin/teams.json
  def create
    @team = Team.new(team_params)
    respond_to do |format|
      if @team.save
        format.html { redirect_to admin_teams_path, notice: 'Team was successfully created.' }
        format.json { render :show, status: :created, location: @team }
      else
        format.html { render :new }
        format.json { render json: @team.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /admin/teams/1
  # PATCH/PUT /admin/teams/1.json
  def update
    respond_to do |format|
      if @team.update(team_params)
        format.html { redirect_to admin_teams_path, notice: 'Team was successfully updated.' }
        format.json { render :show, status: :ok, location: @team }
      else
        format.html { render :edit }
        format.json { render json: @team.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /admin/teams/1
  # DELETE /admin/teams/1.json
  def destroy
    @team.destroy
    respond_to do |format|
      format.html { redirect_to admin_teams_path, notice: 'Team was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_team
      @team = Team.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def team_params
      params.require(:team).permit(:name, mutant_ids: [], task_ids: [])
    end
end

app/helpers/admin/teams_helper.rb
module Admin::TeamsHelper
end

app/views/admin/teams/_form.html.haml
= simple_form_for([:admin,@team]) do |f|
  - if @team.errors.any?
    #error_explanation
      %h2
        = pluralize(@team.errors.count, "error")
        prohibited this team from being saved:
      %ul
        - @team.errors.full_messages.each do |message|
          %li= message
  = f.input :name, input_html: {maxlength: 30}
  = f.association :mutants
  = f.association :tasks
  .actions
    = f.submit( class: "ui submit button")

app/views/admin/teams/edit.html.haml
%h1 Editing admin_team

= render 'form'

= link_to 'Back', admin_teams_path, class: "ui small button blue"

app/views/admin/teams/index.html.haml
%h1.ui.dividing.header Teams
%table.ui.table
  %thead
    %tr
      %th Name
      %th Mutants
      %th Tasks assigned
      %th{colspan: 3}
  %tbody
    - @teams.each do |team|
      %tr
        %td= team.name
        %td
          - team.mutants.each do |mutant|
            = link_to mutant.name, edit_admin_mutant_path(mutant)
            %br/
        %td
          - team.tasks.each do |task|
            = link_to task.name, edit_admin_task_path(task)
            %br/
        %td= link_to 'Edit', edit_admin_team_path(team), {class: "ui small button"}
        %td= link_to 'Destroy', admin_team_path(team), method: :delete, data: { confirm: 'Are you sure?' }, class: "ui small button red" if team.destroyable?
%br/
= link_to 'New Team', new_admin_team_path, class: "ui large button blue"

app/views/admin/teams/new.html.haml
%h1 New admin_team

= render 'form'

= link_to 'Back', admin_teams_path, class: "ui small button blue"

app/views/admin/teams/show.html.haml
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_admin_team_path(@admin_team) %> |
<%= link_to 'Back', admin_teams_path %>