config/routes.rb
Rails.application.routes.draw do


	#cut off www
	constraints(:host => /^www\./) do
		get "(*x)" => redirect { |params, request|
			ap URI.parse(request.url).tap {|url| url.host.sub!('www.', '') }.to_s
			URI.parse(request.url).tap {|url| url.host.sub!('www.', '') }.to_s
		}
	end
	namespace :admin do
		resources :users
		resources :teams 
    resources :mutants
    resources :tasks
		root to: 'teams#index'
	end

	devise_for :users,
		path_names: { sign_in: 'login', sign_out: 'logout', sign_up: 'signup' },
		sign_out_via: [:post, :delete, :get],
		controllers: { registrations: "users/registrations" }

	root to: 'front/landing#index'
end

app/views/layouts/application.html.haml
!!! 5
<!--[if lt IE 7]> <html lang="en" class="no-js lt-ie9 lt-ie8 lt-ie7"> <![endif]-->
<!--[if IE 7]> <html lang="en" class="no-js lt-ie9 lt-ie8"> <![endif]-->
<!--[if IE 8]> <html lang="en" class="no-js lt-ie9"> <![endif]-->
<!--[if gt IE 8]><!-->
%html.no-js(lang = "ru" )
  <!--<![endif]-->
  %head
    %meta{ :charset => "utf-8" }/
    != csrf_meta_tag
    %meta{'http-equiv' => 'X-UA-Compatible', :content => 'IE=edge,chrome=1'}/
    %title Hero control 
    %meta{name:"google-site-verification", content:"REPLACE_ME"}
    = stylesheet_link_tag "frontend", :media => 'all'
    =#%meta{:content=>"width=device-width, initial-scale=1.0", :name=>"viewport"}/
    =# javascript_include_tag 'modernizr'
    = javascript_include_tag 'application'
    /[if lt IE 9]
      = javascript_include_tag "http://ie7-js.googlecode.com/svn/version/2.1(beta4)/IE9.js"
  %body
    %nav.ui.menu
      %h3.header.item Team one dashboard
      = link_to t('admin.teams'), admin_teams_path, class: "item #{"active" if controller_name=="teams"}"
      = link_to t('admin.mutants'), admin_mutants_path, class: "item #{"active" if controller_name=="mutants"}"
      = link_to t('admin.tasks'), admin_tasks_path, class: "item #{"active" if controller_name=="tasks"}"
      - unless current_user
        %a.item.right{href: admin_root_path} Login
      - else
        = link_to t('global.sign_out'), destroy_user_session_path, method: :delete, class: "item right"
    -flash.each do |name, msg|
      .ui.info.message
        .header= name
        = msg
    = yield 

app/views/layouts/front.html.haml
!!! 5
<!--[if lt IE 7]> <html lang="en" class="no-js lt-ie9 lt-ie8 lt-ie7"> <![endif]-->
<!--[if IE 7]> <html lang="en" class="no-js lt-ie9 lt-ie8"> <![endif]-->
<!--[if IE 8]> <html lang="en" class="no-js lt-ie9"> <![endif]-->
<!--[if gt IE 8]><!-->
%html.no-js(lang = "ru" )
  <!--<![endif]-->
  %head
    %meta{ :charset => "utf-8" }/
    != csrf_meta_tag
    %meta{'http-equiv' => 'X-UA-Compatible', :content => 'IE=edge,chrome=1'}/
    %title Hero control 
    %meta{name:"google-site-verification", content:"REPLACE_ME"}
    = stylesheet_link_tag "frontend", :media => 'all'
    =#%meta{:content=>"width=device-width, initial-scale=1.0", :name=>"viewport"}/
    =# javascript_include_tag 'modernizr'
    =# javascript_include_tag 'front'
    /[if lt IE 9]
      = javascript_include_tag "http://ie7-js.googlecode.com/svn/version/2.1(beta4)/IE9.js"
  %body
    %nav.ui.menu
      %h3.header.item Team one dashboard
      %a.item.right{href: admin_root_path} Login

    = yield 